### ISSUE TITLE
Support updates to patch versions

### ISSUE THREAD

**Issue by indradhanush** [kinvolk/kubernetes-the-hab-way#16]
We want to be able to support updating the kubernetes components from one patch version to the next, for eg: `1.11.1` to `1.11.2`.

To do this, the following components would need to be updated one at a time:

- [x] kubelet
- [x] kube-proxy
- [x] kube-apiserver
- [x] kube-controller-manager
- [x] kube-scheduler

This is in no specific order. Each component will likely require it's own plumbing before the component can be updated.

**Comment by indradhanush** [comment]
**Initial findings**

If you load a habitat package in the following way:

```hab svc load origin/pkg/version
```

Then the supervisor updates the package only if a new artifact is available in the same version but with a newer timestamp. To build across versions, ensure that you load the service with:

```hab svc load origin/pkg
```

Also, if you're testing for `1.11.1` to `1.11.2` for instance, make sure that the pkg for `1.11.2` is not promoted to `stable` as the above command would end up pulling the latest package. :)

One workaround for this can be using a custom `channel` by promoting the packages there and loading the services with the `--channel` flag.

**Comment by indradhanush** [comment]
Also, it is important to add the `--strategy` flag while loading the services, without which they won't be updated automatically when a newer artifact is available.

It is a good idea to use the `at-once` strategy for now.

**Comment by kosyfrances** [comment]
In our case, we want to be able to mark the node as unschedulable before doing the update, and using the `--strategy` method does not give flexibility for things you'd like to be done like cordoning the node before an update happens. 

One approach in the script we want to write to handle this manually would be:
- Cordon the node (to mark it as unschedulable)
- Unload the package
- Install an updated version of the package (using hab pkg install)
- Load the installed package

The user would take responsibility of things like backing up (if absolutely necessary) before running the script by hand.

**Comment by kosyfrances** [comment]
Just a thought, do we need to apply previous configuration using hab config apply? I did not do anything extra for kube-proxy though, so I do not know yet if not re-applying configurations after updating will be an issue.

**Comment by indradhanush** [comment]
When testing with `kubelet`, I've been able to get the service up and running without having to apply the config again the second time. So I suppose that it is not required.

**Comment by indradhanush** [comment]
This has been done.
